In [12]:
#Import library
from numpy import array
from keras.models import Sequential
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers import Flatten
from keras.layers import Dense

In [2]:
#Define split function to convert sequence into X and y 
def split_sequence(sequence, n_steps_in, n_steps_out):
  X, y = list (), list ()
  for i in range (len(sequence)):
    end_ix = i + n_steps_in
    out_end_ix = end_ix + n_steps_out
    if out_end_ix > len(sequence):
      break
    seq_x, seq_y = sequence[i: end_ix], sequence[end_ix : out_end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return array(X), array(y)

In [3]:
#Define sequence
seq = [1,2,3,4,5,6,7,8,9,10]

In [4]:
#Define n_steps_in and n_steps_out
n_steps_in, n_steps_out = 3,2

In [7]:
#Split into X and y structure
X, y = split_sequence(seq, n_steps_in, n_steps_out)

In [8]:
#Explore data x and y
print(X.shape, y.shape)
for i in range(len(X)):
  print(X[i], y[i])

(6, 3) (6, 2)
[1 2 3] [4 5]
[2 3 4] [5 6]
[3 4 5] [6 7]
[4 5 6] [7 8]
[5 6 7] [8 9]
[6 7 8] [ 9 10]


In [9]:
#define n_feature
n_feature = 1

In [10]:
#Reshape into 3D structure dataset
X = X.reshape((X.shape[0], X.shape[1], n_feature))

In [16]:
#define model
model = Sequential()
model.add(Conv1D(filters= 64, kernel_size= 2, activation= 'relu', input_shape = (n_steps_in, n_feature)))
model.add(MaxPooling1D(pool_size= 2))
model.add(Flatten())
model.add(Dense(50, activation = 'relu'))
model.add(Dense(n_steps_out))
model.compile(optimizer = 'adam', loss = 'mse')

In [17]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_2 (Conv1D)            (None, 2, 64)             192       
_________________________________________________________________
max_pooling1d_2 (MaxPooling1 (None, 1, 64)             0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 64)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 50)                3250      
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 102       
Total params: 3,544
Trainable params: 3,544
Non-trainable params: 0
_________________________________________________________________


In [21]:
#fit model
model.fit(X, y, epochs= 2000, verbose= 0)

In [22]:
#Demonstrate model to forecast
x_input = array([7, 8, 9])
x_input = x_input.reshape((1, n_steps_in, n_feature))
y_hat = model.predict(x_input, verbose = 0)

In [23]:
print(y_hat)

[[10.066288 11.135838]]
