<a href="https://colab.research.google.com/github/Soniartha/Trading-Strategy/blob/main/MLPs_Jason_Brownlee_Multivariate_Multisteps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#Import Library
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import Dense

In [13]:
#Define function for split multivariate into sample
def split_sequence(sequence, n_steps_in, n_steps_out):
  X, y = list (), list ()
  for i in range (len(sequence)):
    end_ix = i + n_steps_in
    out_end_ix = end_ix + n_steps_out
    if out_end_ix > len(sequence):
      break
    seq_x, seq_y = sequence[i:end_ix, :-1], sequence[end_ix: out_end_ix, -1]
    X.append(seq_x)
    y.append(seq_y)
  return array(X), array(y)

In [7]:
#Define sequental dataset // list and array
in_seq1  = array([10, 20, 30, 40, 50, 60, 70, 80, 90])
in_seq2 = array([15, 25, 35, 45, 55, 65, 75, 85, 95])
out_seq = array([in_seq1[i] + in_seq2[i] for i in range (len(in_seq1))])

In [8]:
#Convert into rows and columng structure (2 Dimensional Structure)// tuple
in_seq1 = in_seq1.reshape((len(in_seq1), 1))
in_seq2 = in_seq2.reshape((len(in_seq2), 1))
out_seq = out_seq.reshape((len(out_seq), 1))

In [9]:
#Horizontal stack // tuple
dataset = hstack((in_seq1, in_seq2, out_seq))

In [11]:
#define n_steps_in and n_steps_out
n_steps_in, n_steps_out = 3,2

In [30]:
#Split multivariate into supervised learning 
X, y = split_sequence(dataset, n_steps_in, n_steps_out)

In [31]:
#Display data
print(X.shape)
for i in range (len(X)):
  print(X[i], y[i])

(5, 3, 2)
[[10 15]
 [20 25]
 [30 35]] [ 85 105]
[[20 25]
 [30 35]
 [40 45]] [105 125]
[[30 35]
 [40 45]
 [50 55]] [125 145]
[[40 45]
 [50 55]
 [60 65]] [145 165]
[[50 55]
 [60 65]
 [70 75]] [165 185]


In [32]:
#Flatten input
x_input = X.shape[1] * X.shape[2]
X = X.reshape((X.shape[0], x_input))
X

array([[10, 15, 20, 25, 30, 35],
       [20, 25, 30, 35, 40, 45],
       [30, 35, 40, 45, 50, 55],
       [40, 45, 50, 55, 60, 65],
       [50, 55, 60, 65, 70, 75]])

In [33]:
#Define model
model = Sequential()
model.add(Dense(100, activation= 'relu', input_dim = x_input))
model.add(Dense(n_steps_out))
model.compile(optimizer = 'adam', loss = 'mse')

In [34]:
#fit model
model.fit(X, y, epochs = 2000, verbose= 0)

In [39]:
#Demonstrate the prediction
x_data = array([[70, 75], [80, 85], [90,95]])
x_data = x_data.reshape((1, x_input))
y_hat = model.predict(x_data, verbose=2)
print(y_hat)

1/1 - 0s
[[207.58017 233.15938]]
