<a href="https://colab.research.google.com/github/Soniartha/Trading-Strategy/blob/main/MLPs_Jason_Brownlee_Univariate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Import library
from numpy import array
from keras.models import Sequential
from keras.layers import Dense

In [11]:
#Split a univariate sequence in to samples
def split_sequence(sequence,n_steps):
  X, y = list (), list ()
  for i in range (len(sequence)):
    #find the end of this pattern
    end_ix = i + n_steps
    #check if we are beyond the sequence
    if end_ix > len(sequence)-1:
      break
    #gather input and output parts of the pattern
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return array(X), array(y)


In [12]:
#Define a sequence
series = [20, 40, 60, 80, 100, 120, 140, 160, 180]

In [5]:
#Define n_steps
n_step = 3

In [15]:
#Split in to supervised learning sample
X,y = split_sequence(series, n_step)
for i in range (len(X)):
  print(X[i], y[i])


[20 40 60] 80
[40 60 80] 100
[ 60  80 100] 120
[ 80 100 120] 140
[100 120 140] 160
[120 140 160] 180


In [29]:
#Multilayer Perceptron (MLP)
model = Sequential()
model.add(Dense(100, activation= 'relu', input_dim = n_step))
model.add(Dense(36))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [30]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 100)               400       
_________________________________________________________________
dense_4 (Dense)              (None, 36)                3636      
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 37        
Total params: 4,073
Trainable params: 4,073
Non-trainable params: 0
_________________________________________________________________


In [31]:
#fit model
model.fit(X, y, epochs=2000, verbose=0)

In [32]:
x_input = array([140, 160, 180])
x_input = x_input.reshape((1, n_step))
y_hat = model.predict(x_input, verbose=0)
print(y_hat)

[[204.77031]]
