<a href="https://colab.research.google.com/github/Soniartha/Trading-Strategy/blob/main/MLPs_Jason_Brownlee_Multistep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Import library
from numpy import array
from keras.models import Sequential
from keras.layers import Dense

In [29]:
#Split a univariate sequence into sample
def split_sequence(sequence, n_steps, n_steps_out):
  X, y = list (), list ()
  for i in range(len(sequence)):
    #find the end of this pattern
    end_ix = i + n_steps
    out_end_ix = end_ix + n_steps_out
    #check if we are beyond the sequence
    if out_end_ix > len(sequence):
      break
    #gather into input and output in this part
    seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix]
    X.append(seq_x)
    y.append(seq_y)
  return array(X), array(y)

In [30]:
#Define input sequence
series = [1,2,3,4,5,6,7,8,9]

In [31]:
#Choose n_steps and n_steps_out
n_steps = 3
n_steps_out = 2

In [33]:
#Split into sample
X, y = split_sequence(series, n_steps, n_steps_out)

#Summarize the data
for i in range (len(X)):
  print(X[i], y[i])

[1 2 3] [4 5]
[2 3 4] [5 6]
[3 4 5] [6 7]
[4 5 6] [7 8]
[5 6 7] [8 9]


In [39]:
model =Sequential()
model.add(Dense(100, activation='relu', input_dim = n_steps))
model.add(Dense(n_steps_out))
model.compile(optimizer = 'adam', loss = 'mse')

In [40]:
#Fit the model
model.fit(X,y, epochs= 2000, verbose=0)

In [42]:
#Demonstrate the prediction
x_input = array([7, 8, 9])
x_input = x_input.reshape((1, n_steps))
y_hat = model.predict(x_input,verbose=0)
print(y_hat)

[[ 9.9998665 11.049721 ]]
